### ISSUE TITLE
asset path must start with the project source root

### ISSUE THREAD

**Issue by Danny-P** [amcharts/amcharts3#198]
I have upgraded amcharts3 to version 3.21.13. Now I get the following error: 

```
The node_modules/amcharts3/amcharts/images asset path must start with the project source root.
Error: The node_modules/amcharts3/amcharts/images asset path must start with the project source root.
    at assetPatterns.map.assetPattern (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/@angular-devkit/build-angular/src/utils/normalize-asset-patterns.js:37:23)
    at Array.map (<anonymous>)
    at Object.normalizeAssetPatterns (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/@angular-devkit/build-angular/src/utils/normalize-asset-patterns.js:30:10)
    at MergeMapSubscriber.check_port_1.checkPort.pipe.operators_1.concatMap [as project] (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:35:467)
    at MergeMapSubscriber._tryNext (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
    at MergeMapSubscriber._next (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/Subscriber.js:64:18)
    at TapSubscriber._next (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/operators/tap.js:62:26)
    at TapSubscriber.Subscriber.next (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/operators/mergeMap.js:84:26)
    at InnerSubscriber._next (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/Subscriber.js:64:18)
    at /mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/operators/mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/operators/mergeMap.js:72:14)
```
Did I miss something?

**Comment by Pauan** [comment]
@Danny-P Could you please post your `.angular-cli.json`?

**Comment by Danny-P** [comment]
I'm using angular 6. Here is my angular.json
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "Assist": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "polyfills": "src/polyfills.ts",
            "assets": [
              "src/assets",
              "src/assets/img/favicon.ico",
              "node_modules/amcharts3/amcharts/images"
            ],
            "styles": [
              "src/assets/css/font-awesome.min.css",
              "src/assets/sass/simple-line-icons.scss",
              "src/assets/sass/bootstrap.scss",
              "src/assets/sass/loader.scss",
              "src/assets/sass/custom-material-theme.scss",
              "node_modules/angular-calendar/dist/css/angular-calendar.css",
              "node_modules/leaflet/dist/leaflet.css",
              "src/assets/sass/style.scss"
            ],
            "scripts": [
              "node_modules/amcharts3/amcharts/amcharts.js",
              "node_modules/amcharts3/amcharts/pie.js",
              "node_modules/amcharts3/amcharts/radar.js",
              "node_modules/amcharts3/amcharts/xy.js",
              "node_modules/amcharts3/amcharts/serial.js",
              "node_modules/amcharts3/amcharts/themes/light.js",
              "node_modules/jspdf/dist/jspdf.min.js"
            ]
          },
          "configurations": {
            "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "Assist:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "Assist:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "Assist:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "karmaConfig": "./karma.conf.js",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "scripts": [
              "node_modules/amcharts3/amcharts/amcharts.js",
              "node_modules/amcharts3/amcharts/pie.js",
              "node_modules/amcharts3/amcharts/radar.js",
              "node_modules/amcharts3/amcharts/xy.js",
              "node_modules/amcharts3/amcharts/serial.js",
              "node_modules/amcharts3/amcharts/themes/light.js",
              "node_modules/jspdf/dist/jspdf.min.js"
            ],
            "styles": [
              "src/assets/css/font-awesome.min.css",
              "src/assets/sass/simple-line-icons.scss",
              "src/assets/sass/bootstrap.scss",
              "src/assets/sass/loader.scss",
              "src/assets/sass/custom-material-theme.scss",
              "node_modules/angular-calendar/dist/css/angular-calendar.css",
              "node_modules/leaflet/dist/leaflet.css",
              "src/assets/sass/style.scss"
            ],
            "assets": [
              "src/assets",
              "src/assets/img/favicon.ico",
              "node_modules/amcharts3/amcharts/images"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": []
          }
        }
      }
    },
    "Assist-e2e": {
      "root": "e2e",
      "sourceRoot": "e2e",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "./protractor.conf.js",
            "devServerTarget": "Assist:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "e2e/tsconfig.e2e.json"
            ],
            "exclude": []
          }
        }
      }
    }
  },
  "defaultProject": "Assist",
  "schematics": {
    "@schematics/angular:component": {
      "prefix": "app",
      "styleext": "scss"
    },
    "@schematics/angular:directive": {
      "prefix": "app"
    }
  }
}
```

**Comment by SergioLabres** [comment]
I got the same error message using Angular 7 and amcharts3 3.21.14.

> 
> 
> I have upgraded amcharts3 to version 3.21.13. Now I get the following error:
> 
> ```
> The node_modules/amcharts3/amcharts/images asset path must start with the project source root.
> Error: The node_modules/amcharts3/amcharts/images asset path must start with the project source root.
>     at assetPatterns.map.assetPattern (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/@angular-devkit/build-angular/src/utils/normalize-asset-patterns.js:37:23)
>     at Array.map (<anonymous>)
>     at Object.normalizeAssetPatterns (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/@angular-devkit/build-angular/src/utils/normalize-asset-patterns.js:30:10)
>     at MergeMapSubscriber.check_port_1.checkPort.pipe.operators_1.concatMap [as project] (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:35:467)
>     at MergeMapSubscriber._tryNext (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
>     at MergeMapSubscriber._next (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
>     at MergeMapSubscriber.Subscriber.next (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/Subscriber.js:64:18)
>     at TapSubscriber._next (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/operators/tap.js:62:26)
>     at TapSubscriber.Subscriber.next (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/Subscriber.js:64:18)
>     at MergeMapSubscriber.notifyNext (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/operators/mergeMap.js:84:26)
>     at InnerSubscriber._next (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/InnerSubscriber.js:25:21)
>     at InnerSubscriber.Subscriber.next (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/Subscriber.js:64:18)
>     at /mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/util/subscribeTo.js:17:28
>     at Object.subscribeToResult (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
>     at MergeMapSubscriber._innerSub (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/operators/mergeMap.js:75:38)
>     at MergeMapSubscriber._tryNext (/mnt/data/daniel/Entwicklung/Sources/MA-Portal_singleOriginal/node_modules/rxjs/internal/operators/mergeMap.js:72:14)
> ```
> 
> Did I miss something?

**Comment by ajay-managaon** [comment]
Have you found a solution for this?
